### PR TITLE
Impacts page

### PR DESCRIPTION
**Pull request by keyualiceli**
#16 
Initial set up of the Impacts page
ps. I'll set up a new issue to collect the actual information of testimonials. Currently I've put placeholders there but we would need actual people's names, their stories/throughts/gains through Tech+, and pictures.

### CODE REVIEW

**Comment by eyhhuang** [comment]
Just gonna leave a comment on how the page looks (and not the code).

1) I noticed that the image for the stats is kind of blurry so we'll definitely want to replace that
2) There is some weird overlap when resizing
image
3) There is a lot of empty space at the bottom 
image
4) If it takes too long to get the testimonials, e.g. we can't get them by the end of the week, then I think we should just comment that section out and only have the impact stats so we can launch the website soon. Or, we can have a nicely stylized "Coming soon" for the testimonials section 

This looks great so far!!

**Review by mahadzaryab1 — COMMENTED** [review]
1. I'm not sure if this is a bug or glitch but there's a slight lag for these images to load. Maybe a life cycle thing?
image
2. I know the stats right now are images but are we going to use React components later? How are we going to deal with changing stats?
3. The growth stories portion looks great!

**Comment by kerry918** [comment]
The whole impacts page looks great to me, the next step would be to solve some small issues that Emily and Mahad mentioned above. 

Overall, it looks really nice!!!

**Review by kerry918 — COMMENTED** [review]
The whole impacts page looks great to me, the next step would be to solve some small issues that Emily and Mahad mentioned above.

Overall, it looks really nice!!!

**Comment by eyhhuang** [comment]
> 2. I know the stats right now are images but are we going to use React components later? How are we going to deal with changing stats?

@mahadzaryab1 I think those stats will remain images for the scope of this term and then in the future we can have an actively updating "dashboard" of stats

**Comment by mahadzaryab1** [comment]
> > 1. I know the stats right now are images but are we going to use React components later? How are we going to deal with changing stats?
> 
> @mahadzaryab1 I think those stats will remain images for the scope of this term and then in the future we can have an actively updating "dashboard" of stats

@eyhhuang Sounds good! I'm excited for that.

**Pull request merged**
