### PR TITLE
LinkedIn update

### PR DESCRIPTION
**Pull request by kerry918**
Added Linkedin links for team members.

### CODE REVIEW

**Review by jingyi2318 — APPROVED** [review]
I went through a few of the links and it's looking good! This isn't a big deal, but an idea is to make the linkedin links a bit more obvious (maybe an icon next to the name or something?? idk haha) since at first I didn't realize our names were linked until I hovered over them. 

I really love the idea to have LinkedIn profiles linked though!! 😻

**Review by mahadzaryab1 — COMMENTED** [review]
This looks awesome! As @jingyi2318 mentioned I definitely think having a LinkedIn icon would be better so the user knows what exactly they are clicking on. [Here](https://www.flaticon.com/free-icon/linkedin_174857) is a link to the LinkedIn SVG icon that you can use. If you scroll down there's some cool ones that are kinda graphic. Other than that, it looks amazing!!

**Comment by eyhhuang** [comment]
> This looks awesome! As @jingyi2318 mentioned I definitely think having a LinkedIn icon would be better so the user knows what exactly they are clicking on. [Here](https://www.flaticon.com/free-icon/linkedin_174857) is a link to the LinkedIn SVG icon that you can use. If you scroll down there's some cool ones that are kinda graphic. Other than that, it looks amazing!!

Instead of downloading an SVG, i recommend using the fontawesome icons where you can just incorporate it into the code like `<i class="fab fa-linkedin-in"></i>`. I think it makes our code cleaner than using a bunch of downloaded images and it's easier for us to swap out icons or add more!
https://fontawesome.com/icons?d=gallery

**Comment by kerry918** [comment]
Yes, I will definitely add the icon, I think there might be one in material UI but I'm not sure, I will also check out what @eyhhuang suggested! Thanks for the suggestion!!

**Pull request merged**
