### PR TITLE
Implemented Resources page

### PR DESCRIPTION
**Pull request by kerry918**
We might need another link to other clubs or organizations, but except for that, everything is completed.

### CODE REVIEW

**Comment by mathurahravigulan** [comment]
Ooh some super helpful resources 🤩❤️

**Review by jingyi2318 — APPROVED** [review]
I just took a look at it and it's looking amazing! I love the cards for our past event resources 🤩 🤩

**Review by mahadzaryab1 — APPROVED** [review]
Looks really great! The only suggestion I have (it's really small) is that you could maybe add the club icon beside the club name? It might just make that part stand out a bit more but it's also the fine the way it is right now. 
image

**Comment by kerry918** [comment]
> Looks really great! The only suggestion I have (it's really small) is that you could maybe add the club icon beside the club name. It might just make that part stand out a bit more but it's also the fine the way it is right now.
> image

Yes, that's definitely a next step that I will improve on. Thanks for that idea!!

**Pull request merged**
