### PR TITLE
Portal 35/scroll bar impact

### PR DESCRIPTION
**Pull request by JamesCahyadi**

### CODE REVIEW

**Comment by jack-lin-jql** [comment]
Can you please link the issue you're closing by using `Close #your_issue_number`

**Comment by JamesCahyadi** [comment]
Close #35

**Comment by JamesCahyadi** [comment]
Close #35

**Review by kerry918 — APPROVED** [review]
Looks great to me! A possible next step could be to set a fixed height for testimonials sections. The content length varies for different people and the arrow keys are moving up and down right now which could possibly be improved.

**Review by jack-lin-jql — APPROVED** [review]
LGTM

**Pull request merged**
